#!/bin/sh
trap 'kill -44 $(pgrep -f lt)' EXIT
trap 'kill -44 $(pgrep -f woof)' INT

[ -z $@ ] && echo "specify file to share or let someone upload to -U" && exit
port=$(port.sh)

lt -p $port &
woof -i 127.0.0.1 -Z -p $port $@ > /dev/null &

while :
do
pgrep -f woof > /dev/null; [ $? = 1 ] && exit
sleep 0.5
done
